FROM archlinux/base

ARG USER=workstation
ARG HOME=/workstation
ARG SCRIPT=https://raw.githubusercontent.com/simonwjackson/dotfiles/master/bin/setup/setup.sh

RUN curl -s "${SCRIPT}" | sh

VOLUME /workstation

EXPOSE 22
