version: '3.3'
services:
  workstation:
    container_name: workstation
    user: $UID:$GID
    working_dir: $HOME
    command: tail -f /dev/null
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN 
    build:
      context: .
    restart: always
