version: '3.3'
services:
  workstation:
    container_name: workstation
    working_dir: /workstation
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN 
    command: tail -f /dev/null
    restart: always
